# Site settings
title: Stuart Hua's Site
auther: Stuart Hua
description: "Stuart Hua | Software Engineer, Programmer"
url: "https://stuarthua.com"

lang: zh_CN

# Contacts
bottom_link:
  github: stuarthua
  mail: stuarthua@duck.com
  # telegram: stuarthua

# SEO
## Google Analytics
ga_track_id: 'G-S1PDL8VX4B'

# Advanced settings
markdown: kramdown
encoding: utf-8
assets: /assets
collections:
  docs:
    output: true

# Exclude from processing.
exclude:
  # - Gemfile
  # - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

# Include files
include:
  - .well-known
