name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 1. 构建 Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 关键步骤 1: 设置 Ruby 环境
      - name: Setup Ruby
        # 使用官方的 setup-ruby action
        uses: ruby/setup-ruby@v1 
        with:
          # 明确指定 Ruby 版本
          ruby-version: '3.3'
          # 运行 'bundle install' 并缓存 gems
          bundler-cache: true

      # 关键步骤 2: 配置 Pages 路径
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # 关键步骤 3: 手动执行 Jekyll 构建
      # 注意：不再使用 actions/jekyll-build-pages@v1
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
          
      # 关键步骤 4: 上传构建产物
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site # Jekyll 默认构建到 _site 目录

  # 2. 部署 Job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
